//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindh_University_Transport_M_S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int Id { get; set; }
        public string P_Name { get; set; }
        public string P_Type { get; set; }
        public string P_Number { get; set; }
        public string P_Photo { get; set; }
        public string P_S_Timing { get; set; }
        public string P_E_Timing { get; set; }
        public string Shift { get; set; }
        public int LocationId { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
