//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindh_University_Transport_M_S.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Transport_ModelContainer : DbContext
    {
        public Transport_ModelContainer()
            : base("name=Transport_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
